apiVersion: v1
kind: Service
metadata:
  name: recharge-service
spec:
  selector:
    app: recharge-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008
