apiVersion: apps/v1
kind: Deployment
metadata:
  name: recharge-deployment
  labels:
    app: recharge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recharge-app
  template:
    metadata:
      labels:
        app: recharge-app
    spec:
      containers:
      - name: recharge-app
        image: rashidali007/recharge-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
